#!/bin/bash
# Install the .NET Version Manager (DNVM)
sudo apt-get install unzip curl
curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | DNX_BRANCH=dev sh && source ~/.dnx/dnvm/dnvm.sh

# Install the .NET Execution Environment (DNX)
sudo apt-get install libunwind8 gettext libssl-dev libcurl4-openssl-dev zlib1g libicu-dev uuid-dev
dnvm upgrade -r coreclr
dnvm upgrade -r mono #dnx for mono not needed

# Install libuv
sudo apt-get install make automake libtool curl
curl -sSL https://github.com/libuv/libuv/archive/v1.8.0.tar.gz | sudo tar zxfv - -C /usr/local/src
cd /usr/local/src/libuv-1.8.0
sh autogen.sh
./configure
make
make install
sudo rm -rf /usr/local/src/libuv-1.8.0 && cd ~/
ldconfig
